### PR TITLE
added custom error messages while ommiting error

### PR DESCRIPTION
**Pull request by rohitjain00**

### CODE REVIEW

**Review by davepuchyr — APPROVED** [review]
@rohitjain00, just out of curiosity, why did you choose python for this?

**Comment by rohitjain00** [comment]
> @rohitjain00, just out of curiosity, why did you choose python for this?

I was more comfortable using python as a scripting language. I tried it with writing a bash script but that was taking too complicated for me and also because the run time of the script was not an issue here.

**Comment by davepuchyr** [comment]
> > @rohitjain00, just out of curiosity, why did you choose python for this?
> 
> I was more comfortable using python as a scripting language. I tried it with writing a bash script but that was taking too complicated for me and also because the run time of the script was not an issue here.

OK, next time let's use node or ts-node.

**Comment by davepuchyr** [comment]
Usurped via https://github.com/iov-one/asset-directory/pull/8.

**Pull request closed without merging**
